### ISSUE TITLE
Exception happening when you forget to put a newline at the end of the config.yml

### ISSUE THREAD

**Issue by derkork** [derkork/simplegen#1]
```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.FileInputStream@50c87b21; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3851)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at com.ancientlightstudios.simplegen.YamlReader.readToPojo(YamlReader.kt:27)
	at com.ancientlightstudios.simplegen.Runner.<init>(Runner.kt:15)
	at com.ancientlightstudios.simplegen.MainKt.main(Main.kt:35)

```

Should give some more friendly error message.

**Comment by derkork** [comment]
Version 1.0.7. has much improved error handling.
