### ISSUE TITLE
Exception when config file does not exist

### ISSUE THREAD

**Issue by derkork** [derkork/simplegen#7]
When the config file does not exist, one gets a rather ugly exception:

```
INFO Reading configuration...
ERROR ERROR unexpected exception: ./config.yml (No such file or directory) 
java.io.FileNotFoundException: ./config.yml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.ancientlightstudios.simplegen.Runner.run(Runner.kt:30)
	at com.ancientlightstudios.simplegen.MainKt.main(Main.kt:44)
INFO There were errors when running.
```

**Comment by derkork** [comment]
Fixed.
